name: mamam

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Code'
        required: true
      pincode:
        description: 'PINN'
        required: true
  
jobs:
  build:
    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2
    - name: Set...
      run: ./es.ps1
    - name: One Two Three...
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Go../
      run: ./loop.ps1
